name: Aprendiendo Github Actions
run-name: Estoy aprendiendo gitHub Actions!!
on: [push]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout "clonar el repositorio"
        uses: actions/checkout@v3
      - name: Definir Variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Correr script
        run: python hola-mundo.py
