name: Triggers
run-name: ¡Estoy aprendiendo a usar diferentes Triggers!
on:
  issues:
    types:
      - [opened, labeled]
jobs:
  Vamos-con-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ejecutar Script
        run: python main.py
